const allgames = [
  {
    id: 41,
    title: "Gori: Cuddly Carnage",
    imageUrl: "/screenshots2/gorimain.jpg",
    description:
      "A futuristic hack-and-slash where you play as a foul-mouthed, skateboarding cat slicing through hordes of mutant toys. Gori: Cuddly Carnage blends high-speed action, neon-soaked visuals, and dark humor into a chaotic and fun experience. ",
    developer: "By Angry Demon Studio",
    genre: "Genre: Action, Hack-and-Slash",
    release: "Release Date: 2023",
    platform: ["PC, PlayStation, Xbox, Nintendo Switch"],
    bannerImage: "/screenshots2/goribanner.jpg",
    screenshots: [
      "/screenshots2/gori1.jpg",
      "/screenshots2/gori2.jpg",
      "/screenshots2/gor3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1299690/Gori_Cuddly_Carnage/",
  },
  {
    id: 42,
    title: "Cavity Busters",
    imageUrl: "/screenshots2/cavitymain.jpg",
    description:
      "A highly unique roguelike where you play as a lone tooth fighting off waves of bacteria in a decaying mouth-world. Its bizarre art style, tight twin-stick shooting mechanics, and inventive enemy designs make it stand out. ",
    developer: "By  SpaceMyFriend",
    genre: "Genre: Roguelike, Bullet Hell",
    release: "Release Date:  March 18, 2023",
    platform: ["PC"],
    bannerImage: "/screenshots2/cavitybanner.jpg",
    screenshots: [
      "/screenshots2/cavity1.jpg",
      "/screenshots2/cavity2.jpg",
      "/screenshots2/cavity3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1084220/Cavity_Busters/",
  },
  {
    id: 43,
    title: "The Excavation of Hob’s Barrow",
    imageUrl: "/screenshots2/hobmain.jpg",
    description:
      "A folk horror point-and-click adventure set in Victorian England. The hand-painted pixel art, haunting music, and eerie atmosphere make this a deeply unsettling yet compelling mystery. ",
    developer: "By Cloak & Dagger Games",
    genre: "Genre: Adventure, Horror",
    release: "Release Date: September 28, 2022",
    platform: ["PC,  Nintendo Switch"],
    bannerImage: "/screenshots2/hobbanner.jpg",
    screenshots: [
      "/screenshots2/hob1.jpg",
      "/screenshots2/hob2.jpg",
      "/screenshots2/hob3.jpg",
    ],
    playLink:
      "https://store.steampowered.com/app/1182310/The_Excavation_of_Hobs_Barrow/",
  },
  {
    id: 44,
    title: "Lunistice",
    imageUrl: "/screenshots2/lunmain.jpg",
    description:
      "A beautifully stylized 3D platformer inspired by PS1 and Sega Saturn aesthetics. With fluid movement, tight platforming, and a dreamy soundtrack, Lunistice is a nostalgic throwback with modern polish. ",
    developer: "By A Grumpy Fox",
    genre: "Genre: 3D Platformer",
    release: "Release Date: November 10, 2022",
    platform: ["PC, Nintendo Switch"],
    bannerImage: "/screenshots2/lunbanner.jpg",
    screenshots: [
      "/screenshots2/lun1.jpg",
      "/screenshots2/lun2.jpg",
      "/screenshots2/lun3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1701800/Lunistice/",
  },
  {
    id: 45,
    title: "SpiderHeck",
    imageUrl: "/screenshots2/spidermain.jpg",
    description:
      "A physics-based brawler where you play as acrobatic spiders wielding laser swords. The fast-paced, chaotic gameplay makes for hilarious and highly competitive multiplayer battles. ",
    developer: "By Neverjam",
    genre: "Genre: Action, Multiplayer",
    release: "Release Date: September 22, 2022",
    platform: ["PC, PlayStation, Xbox, Nintendo Switch"],
    bannerImage: "/screenshots2/spiderbanner.jpg",
    screenshots: [
      "/screenshots2/spider1.jpg",
      "/screenshots2/spider2.jpg",
      "/screenshots2/spider3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1329500/SpiderHeck/",
  },
  {
    id: 46,
    title: "Dap",
    imageUrl: "/screenshots2/dapmain.jpg",
    description:
      "A surreal horror game with Pikmin-style mechanics where you guide tiny creatures through a decaying forest filled with dark, mysterious forces. The eerie visuals and unsettling atmosphere make for a unique and chilling experience. ",
    developer: "By Melting Parrot",
    genre: "Genre: Horror, Action-Adventure",
    release: "Release Date: September 29, 2021",
    platform: ["PC"],
    bannerImage: "/screenshots2/dapbanner.jpg",
    screenshots: [
      "/screenshots2/dap1.jpg",
      "/screenshots2/dap2.jpg",
      "/screenshots2/dap3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1372210/Dap/",
  },
  {
    id: 47,
    title: "Vengeful Guardian: Moonrider",
    imageUrl: "/screenshots2/moonmain.jpg",
    description:
      "A side-scrolling action game inspired by classic 16-bit era titles like Shinobi and Strider. With stunning pixel art, fast-paced combat, and an excellent soundtrack, Moonrider is an adrenaline-fueled retro experience. ",
    developer: "By JoyMasher",
    genre: "Genre: Action, Retro Platformer",
    release: "Release Date: January 12, 2023",
    platform: ["PC, PlayStation, Xbox, Nintendo Switch"],
    bannerImage: "/screenshots2/moonbanner.jpg",
    screenshots: [
      "/screenshots2/moon1.jpg",
      "/screenshots2/moon2.jpg",
      "/screenshots2/moon3.jpg",
    ],
    playLink:
      "https://store.steampowered.com/app/1942010/Vengeful_Guardian_Moonrider/",
  },
  {
    id: 48,
    title: "Dredge",
    imageUrl: "/screenshots2/dredgemain.jpg",
    description:
      "A fishing game with a Lovecraftian horror twist. As you explore the ocean, you’ll uncover dark secrets, eerie creatures, and an unsettling atmosphere hidden beneath the waves. A masterful mix of cozy gameplay and psychological horror. ",
    developer: "By Black Salt Games",
    genre: "Genre: Adventure, Horror, Fishing",
    release: "Release Date: March 30, 2023",
    platform: ["PC,  PlayStation, Xbox, Nintendo Switch"],
    bannerImage: "/screenshots2/dredgebanner.jpg",
    screenshots: [
      "/screenshots2/dredge1.jpg",
      "/screenshots2/dredge2.jpg",
      "/screenshots2/dredge3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1562430/DREDGE/",
  },
  {
    id: 49,
    title: "The Last Spell",
    imageUrl: "/screenshots2/lastmain.jpg",
    description:
      "A tactical roguelike where you defend a city from relentless waves of monstrous hordes. The strategic gameplay, deep RPG mechanics, and dark fantasy setting make it an addicting challenge for fans of turn-based combat. ",
    developer: "By Ishtar Games",
    genre: "Genre: Strategy, Roguelike",
    release: "Release Date: March 9, 2023",
    platform: ["PC, PlayStation, Nintendo Switch"],
    bannerImage: "/screenshots2/lastbanner.jpg",
    screenshots: [
      "/screenshots2/last1.jpg",
      "/screenshots2/last2.jpg",
      "/screenshots2/last3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1105670/The_Last_Spell/",
  },
  {
    id: 50,
    title: "Tiny Rogues",
    imageUrl: "/screenshots2/tinymain.jpg",
    description:
      "A pixel-art dungeon-crawling roguelike with randomized loot, class-based progression, and intense action combat. The blend of RPG depth and arcade-like gameplay makes it highly addictive. ",
    developer: "By Rubidev",
    genre: "Genre: Roguelike, Action RPG",
    release: "Release Date: September 23, 2022 ",
    platform: ["PC"],
    bannerImage: "/screenshots2/tinybanner.jpg",
    screenshots: [
      "/screenshots2/tiny1.jpg",
      "/screenshots2/tiny2.jpg",
      "/screenshots2/tiny3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/2088570/Tiny_Rogues/",
  },
];

export default allgames;
