const allgames = [
  {
    id: 21,
    title: "Sludge Life 2",
    imageUrl: "/screenshots/sludgemain.jpg",
    description:
      "A weird and wild first-person open-world game where you explore a grimy, graffiti-filled world. Its satirical humor, funky characters, and immersive setting make it a standout indie experience. ",
    developer: "By Terri Vellmann & Doseone",
    genre: "Genre: Open-World, Exploration",
    release: "Release Date:   June 27, 2023",
    platform: ["PC"],
    bannerImage: "/screenshots/sludgebanner.jpg",
    screenshots: [
      "/screenshots/sludge1.jpg",
      "/screenshots/sludge2.jpg",
      "/screenshots/sludge3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/2275150/SLUDGE_LIFE_2/",
  },
  {
    id: 22,
    title: "Lunacid",
    imageUrl: "/screenshots/lunacidmain.jpg",
    description:
      "A dark, atmospheric first-person dungeon-crawling RPG inspired by King’s Field and other classic FromSoftware titles. Lunacid offers deep exploration, eerie environments, and old-school gameplay with a fresh indie twist. ",
    developer: "By  Kira LLC",
    genre: "Genre: Dungeon Crawler, RPG",
    release: "Release Date:  March 30, 2023 (Full Release)",
    platform: ["PC"],
    bannerImage: "/screenshots/lunacidbanner.jpg",
    screenshots: [
      "/screenshots/lunacid1.jpg",
      "/screenshots/lunacid2.jpg",
      "/screenshots/lunacid3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1745510/Lunacid/",
  },
  {
    id: 23,
    title: "Garden Story",
    imageUrl: "/screenshots/gardenmain.jpg",
    description:
      "A wholesome action RPG where you play as a tiny grape tasked with restoring a crumbling community. Garden Story delivers charming pixel art, satisfying quests, and a relaxing yet engaging adventure. ",
    developer: "By Picogram",
    genre: "Genre: Adventure, RPG",
    release: "Release Date:  August 11, 2021",
    platform: ["PC, Nintendo Switch"],
    bannerImage: "/screenshots/gardenbanner.jpg",
    screenshots: [
      "/screenshots/garden1.jpg",
      "/screenshots/garden2.jpg",
      "/screenshots/garden3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1062140/Garden_Story/",
  },
  {
    id: 24,
    title: "Below the Stone",
    imageUrl: "/screenshots/belowmain.jpg",
    description:
      "A pixel-art roguelike dungeon crawler with deep mining mechanics and high-risk, high-reward gameplay. Each descent into the underground is unpredictable, filled with hidden treasures and lurking dangers. ",
    developer: "By Strollart Studios",
    genre: "Genre: Roguelike, Dungeon Crawler",
    release: "Release Date: November 17, 2023",
    platform: ["PC"],
    bannerImage: "/screenshots/belowbanner.jpg",
    screenshots: [
      "/screenshots/below1.jpg",
      "/screenshots/below2.jpg",
      "/screenshots/below3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1170230/Below_the_Stone/",
  },
  {
    id: 25,
    title: "NecroBouncer",
    imageUrl: "/screenshots/necromain.jpg",
    description:
      "You play as a necromancer bouncer keeping the underworld’s nightclub under control in this roguelike action game. With chaotic combat, neon visuals, and an electrifying soundtrack, it’s a fast-paced thrill ride. ",
    developer: "By Alchemy Sheep",
    genre: "Genre: Roguelike, Action",
    release: "Release Date: December 8, 2022",
    platform: ["PC"],
    bannerImage: "/screenshots/necrobanner.jpg",
    screenshots: [
      "/screenshots/necro1.jpg",
      "/screenshots/necro2.jpg",
      "/screenshots/necro3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1786830/NecroBouncer/",
  },
  {
    id: 26,
    title: "Paper Trail",
    imageUrl: "/screenshots/papermain.jpg",
    description:
      "A beautiful hand-drawn puzzle game where you fold and manipulate paper to explore the world and solve puzzles. The story-driven experience is heartfelt, artistic, and wonderfully unique. ",
    developer: "By Newfangled Games",
    genre: "Genre: Puzzle, Adventure",
    release: "Release Date: May 21, 2024",
    platform: ["PC,  PlayStation, Xbox, Nintendo Switch"],
    bannerImage: "/screenshots/paperbanner.jpg",
    screenshots: [
      "/screenshots/paper1.jpg",
      "/screenshots/paper2.jpg",
      "/screenshots/paper3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1889740/Paper_Trail/",
  },
  {
    id: 27,
    title: "Undetected",
    imageUrl: "/screenshots/undetectmain.jpg",
    description:
      "A stealth-action game inspired by Metal Gear Solid, focusing on sneaky tactics, clever distractions, and old-school spy gameplay. It’s a hidden gem for fans of classic stealth mechanics. ",
    developer: "By Antonio Freyre",
    genre: "Genre: Stealth, Action",
    release: "Release Date: September 30, 2022",
    platform: ["PC, PlayStation, Xbox"],
    bannerImage: "/screenshots/undetectbanner.jpg",
    screenshots: [
      "/screenshots/undetect1.jpg",
      "/screenshots/undetect2.jpg",
      "/screenshots/undetect3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1715350/UNDETECTED/",
  },
  {
    id: 28,
    title: "The Last Worker",
    imageUrl: "/screenshots/lastmain.jpg",
    description:
      "A satirical, first-person adventure that critiques the rise of automation and corporate dystopias. With a unique comic-book art style and thought-provoking narrative, it’s a truly one-of-a-kind indie experience. ",
    developer: "By Oiffy, Wolf & Wood Interactive",
    genre: "Genre: Narrative Adventure",
    release: "Release Date: March 30, 2023",
    platform: ["PC,  PlayStation, Xbox, Nintendo Switch"],
    bannerImage: "/screenshots/lastbanner.jpg",
    screenshots: [
      "/screenshots/last1.jpg",
      "/screenshots/last2.jpg",
      "/screenshots/last3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1579280/The_Last_Worker/",
  },
  {
    id: 29,
    title: "Unwording",
    imageUrl: "/screenshots/unwordmain.jpg",
    description:
      "A minimalist, emotional puzzle game that explores mental health through word-based mechanics. Its clever design and uplifting message make it a must-play for those who love introspective games. ",
    developer: "By Frostwood Interactive",
    genre: "Genre: Puzzle, Narrative",
    release: "Release Date: April 27, 2023",
    platform: ["PC"],
    bannerImage: "/screenshots/unwordbanner.jpg",
    screenshots: [
      "/screenshots/unword1.jpg",
      "/screenshots/unword2.jpg",
      "/screenshots/unword3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1974250/Unwording/",
  },
  {
    id: 30,
    title: "Thirsty Suitors",
    imageUrl: "/screenshots/thirstymain.jpg",
    description:
      "A vibrant, story-rich RPG about culture, relationships, and self-discovery, blending turn-based battles with skateboarding mechanics and witty humor. Its colorful art style and South Asian cultural themes make it a refreshing and standout indie title. ",
    developer: "By Outerloop Games",
    genre: "Genre: RPG, Narrative",
    release: "Release Date: November 2, 2023",
    platform: ["PC,  PlayStation , Xbox, Nintendo Switch"],
    bannerImage: "/screenshots/thirstybanner.jpg",
    screenshots: [
      "/screenshots/thirsty1.jpg",
      "/screenshots/thirsty2.jpg",
      "/screenshots/thirsty3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1617220/Thirsty_Suitors/",
  },
  // Add more games as needed
];

export default allgames;
