const archives = [
  {
    id: 1,
    title: "Tunic",
    imageUrl: "/screenshots/tunicmain.jpg",
    description:
      "Tunic captures the essence of classic adventure games like The Legend of Zelda but with a unique flair. The game’s isometric visuals are stunning, and its clever puzzles and cryptic in-game manual make for an unforgettable journey.",
    developer: "By Andrew Shouldice",
    genre: "Genre: Action-Adventure",
    release: "Release Date:  March 16, 2022",
    platform: ["PC", "Xbox", "PlayStation", "Nintendo Switch"],
    bannerImage: "/screenshots/tunicbanner.jpg",
    screenshots: [
      "/screenshots/tunic1.jpg",
      "/screenshots/tunic2.jpg",
      "/screenshots/tunic3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/553420/TUNIC/",
  },
  {
    id: 2,
    title: "Hyper Light Drifter",
    imageUrl: "/screenshots/hypermain.jpg",
    description:
      "This neon-soaked, pixel-art action RPG is a visual masterpiece with fast-paced combat and a story told through gorgeous imagery. Its melancholic atmosphere keeps you glued to its mysterious world.",
    developer: "By Heart Machine",
    genre: "Genre: Action RPG",
    release: "Release Date: March 31, 2016",
    platform: ["PC", "Switch", "PlayStation", "Xbox"],
    bannerImage: "/screenshots/hyperbanner.jpg",
    screenshots: [
      "/screenshots/hyper1.jpg",
      "/screenshots/hyper2.jpg",
      "/screenshots/hyper3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/257850/Hyper_Light_Drifter/",
  },
  {
    id: 3,
    title: "A Short Hike",
    imageUrl: "/screenshots/hikemain.jpg",
    description:
      "A bite-sized exploration game that’s brimming with charm. With low-poly visuals, relaxing gameplay, and a heartwarming story, A Short Hike is a delightful experience for all ages.",
    developer: "By Adam Robinson-Yu",
    genre: "Genre: Adventure",
    release: "Release Date: July 30, 2019",
    platform: ["PC", "Switch", "PlayStation", "Xbox"],
    bannerImage: "/screenshots/hikebanner.jpg",
    screenshots: [
      "/screenshots/hike1.jpg",
      "/screenshots/hik2.jpg",
      "/screenshots/hik3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1055540/A_Short_Hike/",
  },
  {
    id: 4,
    title: "Eastward",
    imageUrl: "/screenshots/eastmain.jpg",
    description:
      " This pixel-art RPG blends whimsical storytelling with challenging combat and puzzles. Its beautifully crafted world feels alive, and the chemistry between the main characters, John and Sam, is heartwarming.",
    developer: "By Pixpil",
    genre: "Genre: Adventure RPG",
    release: "Release Date: September 16, 2021",
    platform: ["PC", "Switch"],
    bannerImage: "/screenshots/eastbanner.jpg",
    screenshots: [
      "/screenshots/east1.jpg",
      "/screenshots/east2.jpg",
      "/screenshots/east3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/977880/Eastward/",
  },
  {
    id: 5,
    title: " Spiritfarer",
    imageUrl: "/screenshots/spiritmain.jpg",
    description:
      "A cozy management game about ferrying souls to the afterlife. Spiritfarer balances heartwarming interactions with meaningful farewells in a way that’s both relaxing and deeply emotional. ",
    developer: "By Thunder Lotus Games",
    genre: "Genre: Management, Simulation",
    release: "Release Date: August 18, 2020",
    platform: ["PC", "PlayStation", "Xbox", "Switch"],
    bannerImage: "/screenshots/spiritbanner.jpg",
    screenshots: [
      "/screenshots/spirit1.jpg",
      "/screenshots/spirit2.jpg",
      "/screenshots/spirit3.jpg",
    ],
    playLink:
      "https://store.steampowered.com/app/972660/Spiritfarer_Farewell_Edition/",
  },
  {
    id: 6,
    title: "Hades",
    imageUrl: "/screenshots/hadesmain.jpg",
    description:
      "A masterclass in roguelike design, Hades offers fast-paced combat, a compelling story, and rich characters. Supergiant Games created a near-perfect loop of progression and replayability. ",
    developer: "By Supergiant Games",
    genre: "Genre: Roguelike",
    release: "Release Date:  September 17, 2020",
    platform: ["PC", "PlayStation", "Xbox", "Switch"],
    bannerImage: "/screenshots/hadesbanner.jpg",
    screenshots: [
      "/screenshots/hades1.jpg",
      "/screenshots/hades2.jpg",
      "/screenshots/hades3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1145360/Hades/",
  },
  {
    id: 7,
    title: "The Pathless",
    imageUrl: "/screenshots/pathmain.jpg",
    description:
      "This action-adventure game combines fluid archery mechanics with an open world that encourages exploration. Its minimalist storytelling and stunning landscapes are unforgettable.",
    developer: "By Giant Squid",
    genre: "Genre:  Action-Adventure",
    release: "Release Date: November 12, 2020",
    platform: ["PC", "PlayStation", "Xbox", "Switch"],
    bannerImage: "/screenshots/pathbanner.jpg",
    screenshots: [
      "/screenshots/path1.jpg",
      "/screenshots/path2.jpg",
      "/screenshots/path3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/1492680/The_Pathless/",
  },
  {
    id: 8,
    title: "Celeste",
    imageUrl: "/images/celeste.PNG",
    description:
      "This emotional platformer tells a story of mental health and perseverance while delivering tight, challenging gameplay. Each level is crafted with care, offering both difficulty and depth. ",
    developer: "By Maddy Makes Games",
    genre: "Genre: Platformer",
    release: "Release Date: January 25, 2018",
    platform: ["PC", "Nintendo Switch", "PlayStation", "Xbox"],
    bannerImage: "/screenshots/celestebanner.jpg",
    screenshots: [
      "/screenshots/celeste1.jpg",
      "/screenshots/celeste2.jpg",
      "/screenshots/celeste3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/504230/Celeste/",
  },
  {
    id: 9,
    title: "Night in the Woods",
    imageUrl: "/screenshots/nightmain.jpg",
    description:
      "A story-driven adventure with quirky characters and a heartfelt narrative. Its exploration of small-town life and mental health issues feels authentic and resonates deeply. ",
    developer: "By Infinite Fall",
    genre: "Genre: Adventure",
    release: "Release Date: February 21, 2017",
    platform: ["PC", "Nintendo Switch", "PlayStation", "Xbox"],
    bannerImage: "/screenshots/nightbanner.jpg",
    screenshots: [
      "/screenshots/night1.jpg",
      "/screenshots/night2.jpg",
      "/screenshots/night3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/481510/Night_in_the_Woods/",
  },
  {
    id: 10,
    title: "Wildermyth",
    imageUrl: "/screenshots/wildmain.jpg",
    description:
      "Wildermyth is a tactical RPG that blends procedural storytelling with unique character-driven narratives. Every decision you make influences your party members, who age, grow, and even retire. Its blend of tactical combat and emergent storytelling creates an experience that feels deeply personal and endlessly replayable. ",
    developer: "By Worldwalker Games",
    genre: "Genre: Tactical RPG",
    release: "Release Date: June 15, 2021",
    platform: ["PC"],
    bannerImage: "/screenshots/wildbanner.jpg",
    screenshots: [
      "/screenshots/wild1.jpg",
      "/screenshots/wild2.jpg",
      "/screenshots/wild3.jpg",
    ],
    playLink: "https://store.steampowered.com/app/763890/Wildermyth/",
  },
];

export default archives;
